name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
       name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: "3.8"  

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dlskawo0409/github-actions-app
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ DOCKER_METADATA_OUTPUT_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
